### ISSUE TITLE
Is it possible to control each wheel separately with python?

### ISSUE THREAD

**Issue by v24483089** [GuiRitter/OpenBase#11]
Hello,
Is it possible to control each wheel separately with python?
Where should I start ?

**Comment by GuiRitter** [comment]
Hi there.

I suppose it should be possible. Unfortunately, I never worked with ROS with Python, so I can't help you with this language specifically.

But what I can tell you is that, once you launch this project, ROS will create topics that you can publish to, where you can send movement commands to control the robot. The Python process doesn't even need to be on the same machine as the one where the robot is running.

So, as long as your Python code can publish to topics, you can control this robot. To control the wheels, you need to send messages according to the format specified by `Movement.msg` and `Velocity.msg`.

If you haven't already, I suggest you should start with ROS tutorials to get to know the most important ROS concepts. Then, try to use the command line ROS tools that show the available topics and try to control the robot from there before writing any program. The files in the `script` folder have examples on how to publish to topics via the command line.

If you still have questions, feel free to ask them. Otherwise, remember to close the issue when you've accomplished your objective.

**Comment by v24483089** [comment]
Thanks, it is very helpful to me.
