### ISSUE TITLE
Is it possible to control the rollers on the wheels separately?

### ISSUE THREAD

**Issue by alexdewar** [GuiRitter/OpenBase#12]
Currently it seems like you can only set the forward velocities for each of the three wheels, but not the rollers. I'm working with a robot that has Mecanum wheels and it would be really great if I could figure out how to simulate this aspect of it.

Thanks for publishing all this code!

**Comment by GuiRitter** [comment]
Hi there.

You're welcome!

It never occurred to me that something like this would be wanted by someone, so I can't give you a definite answer, but I suppose it should be possible.

If you're working with the Gazebo version, I think all it takes is to change the plugin code to call `*Joint->GetJoint("roller_joint_name");` to get a reference to each roller, then you can set their velocities in the same way.

If you're working with the ROS version, you'll have to:
- edit the `.urdf.xacro` files to add `<transmission>` tags to each roller;
- edit `config/joint_velocity.yaml` to add a controller to each roller joint;
- either publish to the roller controller topics directly or edit some more files to do this more automatically:
   - the files in `msg` to define how you will control them;
   - `src/main.cpp` to answer to the messages above.

Quite a bit of work, but should be possible.

If you still have questions, feel free to ask them. Otherwise, remember to close the issue when you've accomplished your objective.

**Comment by alexdewar** [comment]
Yeah this is a somewhat strange request, motivated by my lack of understanding of how Mecanum wheels actually work :wink:

Thanks for your extensive reply anyway though!
