### ISSUE TITLE
Don't work on RViz

### ISSUE THREAD

**Issue by Kenjiro-Minamikawa** [GuiRitter/OpenBase#22]
Hi, i can control omni robot on Gazebo, but i can't control on RViz.
First, i launched `open_base velocity\ controller.launch` .
Then, i launched  `open_base rviz.launch` .
The robot model are exist on Gazebo and RViz.
But when i send command using rostopic pub, robot move on Gazebo but not on Rviz.
i hope someone teach me how to move on RViz
Thanks.

**Comment by GuiRitter** [comment]
[](url)Hi there!

First and foremost, sorry for the late reply. I've had very little free time as of lately.

[RViz](http://wiki.ros.org/rviz) is just a visualization tool. You shouldn't be able to control any robot in there.

´open_base velocity\ controller.launch´ contains all that is necessary to get a working robot in Gazebo. `open_base rviz.launch` is just to see how the robot will be rendered and is not meant to be controllable or to interact with other `launch` files.

Maybe it should be possible to manually move the joints in RViz but this would be just to check if the joints are configured as intended. I could check to be sure but I need to reinstall my ROS environment because I got a new computer.

Also, if you haven't done so already, I would recommend a careful read through the beginning of [ROS's documentation](https://wiki.ros.org/) to ensure that you know all the basic concepts.
